services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "pdm_minio"
      MINIO_ROOT_PASSWORD: "pdm_minio"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
        - pdmnet

volumes:
  minio-data:

networks:
  pdmnet:
    external: true
